#!/bin/bash

if [ "$#" -ne 1 ]
then
	echo "Usage: ${0} <branch>"
	exit 1
fi

branch=$1

command="git checkout ${branch}"

echo "Top:"
${command}
echo

git submodule foreach --recursive "
	${command} || true;
	echo;
"
