#!/bin/bash

if [ "$#" -ne 1 ]
then
	echo "Usage: ${0} \"Commit comment...\""
	exit 1
fi

comment=$1
echo "commit comment: ${comment}"

`dirname $0`/utils/gitHeader
git commit -m "${comment}" || true
