#!/bin/bash

if [ "$#" -ne 1 ]
then
    comment="Working."
else
    comment=$1
fi

# comment=$1
# echo "comment: ${comment}"

script="commit"
dir=`dirname $0`
"${dir}/utils/scriptTopLast" "${dir}/${script}" "${comment}"
