#!/bin/bash

if [ "$#" -ne 1 ]
then
    comment="Working."
else
    comment=$1
fi

# echo "commit comment: ${comment}"

`dirname $0`/utils/gitHeader
git add --verbose .
git commit -a -m "${comment}" || true
