#!/bin/bash

if [ "$#" -ne 1 ]
then
	echo "Usage: ${0} \"Commit comment...\""
	exit 1
fi

comment=$1
echo "comment: ${comment}"

script="commit"
dir=`dirname $0`
"${dir}/utils/scriptTopLast" "${dir}/${script}" "${comment}"
