#!/bin/bash

SETTINGS="settings.xcconfig"

if [ -e ${SETTINGS} ]; then
    echo "Using ${SETTINGS}"
    swift package generate-xcodeproj --xcconfig-overrides ${SETTINGS}
else
    echo "Using default settings"
    swift package generate-xcodeproj
fi
