#!/bin/bash

DerivedData=`defaults read com.apple.dt.Xcode IDECustomDerivedDataLocation 2> /dev/null`
if [ -z "${DerivedData}" ]
then
    DerivedData="~/Library/Developer/Xcode/DerivedData"
fi

echo "Deleting: ${DerivedData}"
rm -rf ${DerivedData}
